### ISSUE TITLE
Featured Items

### ISSUE THREAD

**Issue by jesseparent** [jesseparent/garage-sale#11]
As a user, I must be able to see the top 4 items listed for sale: Whether I am logged in or not, I must be able to reach the landing page. This page must list the 4 most recent items for sale in the most recent order.

**Comment by cornwalljeremy** [comment]
I have sorted the featured items. It pulls the three most recent uploads to the database and displays a brief version of them on the front page. When you click on the card it takes you to the page of full detail for the item.
