### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by jesseparent** [jesseparent/garage-sale#15]
As a user, I must be allowed to search for specific items: I must have a search box at the top of the page that will allow me to do a specific search for the item I am looking for. If there are matching items, they must be displayed. If there are no matching items, I must be given a notification.

**Comment by janimuhlestein** [comment]
I think this will be pretty simple: create a query that accepts a search argument.

**Comment by janimuhlestein** [comment]
https://www.howtographql.com/react-apollo/7-filtering-searching-the-list-of-links/

**Comment by janimuhlestein** [comment]
Completed.
